# Generated by Django 2.0 on 2019-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=50)),
                ('street', models.CharField(default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100, null=True)),
                ('state', models.CharField(default='', max_length=100, null=True)),
                ('zipc', models.IntegerField(default='', null=True)),
                ('country', models.CharField(default='', max_length=50, null=True)),
                ('byScrapy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Adress',
                'ordering': ['zipc'],
            },
        ),
    ]
