# Generated by Django 2.0 on 2019-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacleaning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='zipc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
